services:
  mongo:
    image: mongo:latest
    restart: always
    env_file: 
      - path: ./api/.env.local
        required: true
      - path: ./api/.env.prod
        required: false
    networks:
      - back_network

  backend:
    container_name: backend
    build:
      context: api
      dockerfile: Dockerfile
    env_file: 
      - path: ./api/.env.local
        required: true
      - path: ./api/.env.prod
        required: false
    restart: always
    networks:
      - front_network
      - back_network
    depends_on:
      - mongo
    develop:
      watch:
        - action: sync
          path: ./api
          target: /code

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file: 
      - path: ./frontend/.env.local
        required: true
      - path: ./frontend/.env.prod
        required: false
    restart: always
    networks:
      - front_network
    ports:
      - 80:3000
      - 443:3000
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app

networks:
  front_network:
  back_network: