services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    env_file: 
      - path: ./api/.env.local
        required: true
    ports:
      - 27017:27017 # to open db for localhost
    volumes:
      - data-vol:/data/db
    networks:
      - back_network

  backend:
    container_name: backend
    build:
      context: api
      dockerfile: Dockerfile
    env_file: 
      - path: ./api/.env.local
        required: true
    restart: always
    ports:
      - 8000:8000
    networks:
      - front_network
      - back_network
    depends_on:
      - mongo
    develop:
      watch:
        - action: sync
          path: ./api
          target: /code

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
         - NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
    restart: always
    networks:
      - front_network
    ports:
      - 80:3000
      - 443:3000
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app

  ai:
    container_name: ai
    build:
      context: ai
      dockerfile: Dockerfile
    env_file: 
      - path: ./ai/.env.local
        required: true
    restart: always
    networks:
      - front_network
    ports:
      - 4000:4000
    develop:
      watch:
        - action: sync
          path: ./ai
          target: /app

networks:
  front_network:
  back_network:

volumes:
  data-vol: