name: "Project CI"

on:
  push:
    branches:
      - main

jobs:
  files-changed:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}
      infra: ${{ steps.changes.outputs.infra }}
      ai: ${{ steps.changes.outputs.ai }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check for folder file changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            backend:
              - 'api/**'
            frontend:
              - 'frontend/**'
            infra:
              - 'infra/**'
            ai:
              - 'ai/**'

  build-frontend:
    needs: files-changed
    if: needs.files-changed.outputs.frontend == 'true'
    uses: ./.github/workflows/build-frontend.yaml

  deploy-frontend:
    needs: build-frontend
    uses: ./.github/workflows/deploy.yaml
    with:
      dockerfile: frontend/Dockerfile
      context: frontend
      image: leaders.cr.cloud.ru/leaders-hack-2024-gb/frontend
    secrets: inherit

  deploy-backend:
    needs: files-changed
    if: needs.files-changed.outputs.backend == 'true' || needs.files-changed.outputs.infra == 'true'
    uses: ./.github/workflows/deploy.yaml
    with:
      dockerfile: api/Dockerfile
      context: api
      image: leaders.cr.cloud.ru/leaders-hack-2024-gb/backend
    secrets: inherit

  deploy-ai:
    needs: files-changed
    if: needs.files-changed.outputs.ai == 'true'
    uses: ./.github/workflows/deploy.yaml
    with:
      dockerfile: ai/Dockerfile
      context: ai
      image: leaders.cr.cloud.ru/leaders-hack-2024-gb/ai-worker
    secrets: inherit