name: "Project CI"

on:
  push:
    branches:
      - main

jobs:
  files-changed:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}
      infra: ${{ steps.changes.outputs.infra }}
      ai: ${{ steps.changes.outputs.ai }}
      scheduler: ${{ steps.changes.outputs.scheduler }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check for folder file changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            backend:
              - 'api/**'
            frontend:
              - 'frontend/**'
            infra:
              - 'infra/**'
            ai:
              - 'ai/**'
            scheduler:
              - 'scheduler/**'

  build-frontend:
    needs: files-changed
    if: needs.files-changed.outputs.frontend == 'true'
    uses: ./.github/workflows/build-frontend.yaml

  build-and-push-frontend:
    name: Frontend
    needs: build-frontend
    uses: ./.github/workflows/build-and-push.yaml
    with:
      dockerfile: frontend/Dockerfile
      context: frontend
      image: leaders.cr.cloud.ru/leaders-hack-2024-gb/frontend
    secrets: inherit

  build-and-push-backend:
    name: Backend
    needs: files-changed
    if: needs.files-changed.outputs.backend == 'true' || needs.files-changed.outputs.infra == 'true'
    uses: ./.github/workflows/build-and-push.yaml
    with:
      dockerfile: api/Dockerfile
      context: api
      image: leaders.cr.cloud.ru/leaders-hack-2024-gb/backend
    secrets: inherit

  build-and-push-ai:
    name: AI
    needs: files-changed
    if: needs.files-changed.outputs.ai == 'true'
    uses: ./.github/workflows/build-and-push.yaml
    with:
      dockerfile: ai/Dockerfile
      context: ai
      image: leaders.cr.cloud.ru/leaders-hack-2024-gb/ai-worker
    secrets: inherit

  build-and-push-scheduler:
    name: Scheduler
    needs: files-changed
    if: needs.files-changed.outputs.scheduler == 'true'
    uses: ./.github/workflows/build-and-push.yaml
    with:
      dockerfile: scheduler/Dockerfile
      context: scheduler
      image: leaders.cr.cloud.ru/leaders-hack-2024-gb/scheduler
    secrets: inherit

  deploy-all:
    name: Deploy app
    needs: [build-and-push-ai, build-and-push-backend, build-and-push-frontend, build-and-push-scheduler]
    if:  ${{ always() && !failure() && !cancelled() }}
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit