name: 'Project deploy'

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      image:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image }}
          tags: |
            type=raw,value=release-{{date 'YYYYMMDD-HHmm'}}-{{sha}}
            type=raw,value=latest
      - name: Login to docker registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: leaders.cr.cloud.ru
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL }}"

      - name: Clean up
        run: |
          docker rmi $DOCKER_METADATA_OUTPUT_TAGS
          docker builder prune -f

  deploy:
      needs: build-and-push
      name: deploy backend
      if: inputs.context == 'api'
      runs-on: ubuntu-latest

      steps:
      - name: connect and pull
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo docker pull leaders.cr.cloud.ru/leaders-hack-2024-gb/backend:latest
            sudo docker run -d -t -i \
              -e MONGO_HOST=${{ secrets.MONGO_HOST }} \ 
              -e MONGO_USERNAME=${{ secrets.MONGO_USERNAME }} \
              -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
              -e MONGO_DATABASE=${{ secrets.MONGO_DATABASE }} \
              -e JWT_PUBLIC_KEY_PATH='~/.ssh/jwtRS256.key.pub' \
              -e JWT_PRIVATE_KEY_PATH='~/.ssh/jwtRS256.key' \
              -e JWT_ALGORITHM='HS256' \
              -e ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }} \
              --name leaders_backend \
              leaders.cr.cloud.ru/leaders-hack-2024-gb/backend:latest